version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: kurye_postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: kurye_user
      POSTGRES_PASSWORD: kurye_password
      POSTGRES_DB: kurye_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - kurye_network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U kurye_user -d kurye_db']
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: kurye_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '5050:80'
    depends_on:
      - postgres
    networks:
      - kurye_network

networks:
  kurye_network:
    driver: bridge

volumes:
  postgres_data:
